---
- hosts: localhost
  connection: local

  tasks:
  - name: Create EC2 instances
    amazon.aws.ec2_instance:
      name: "Ansible-instance"
      key_name: "jenkins"
      instance_type: t2.micro
      security_group: default
      region: us-east-2
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "ami-036841078a4b68e14"
   